[platformio]
; Change this to d1_mini when you want to flash the ESP8266
default_envs = d1_mini

[env]
framework = arduino
monitor_speed = 74800
board_build.filesystem = littlefs

; Shared libraries for both boards
lib_deps =
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    knolleary/PubSubClient
    adafruit/Adafruit GFX Library 
    adafruit/Adafruit IS31FL3731 Library
    ayushsharma82/ElegantOTA

[env:lolin32]
platform = espressif32
board = lolin32

[env:d1_mini]
platform = espressif8266
board = d1_mini
upload_port = /dev/cu.usbserial-210

